지난번 빈도 기반 벡터화 방법을 공부했다.

# 학습목표
분산 기반 벡터화 방법(Word2Vec)을 케라스 모델에 임포팅할 수 있다.


분산 기반 벡터화의 대표, Word2Vec은 target단어 주변 단어에 의해 표현이 결정된다.
* Word2Vec의 벡터화 방법
  1. CBow 방법  
    문장에서 마스킹된 단어의 주변단어를 읽고 마스킹된 단어를 예측하는 과정

  2. skip-gram 방법  
    문장에서 표시된 단어를 읽고 마스킹된 주변 단어를 예측하는 과정
    


### gensim 패키지로 구현하는 word2vec

In [4]:
# !pip install gensim --upgrade
# !pip install --upgrade numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 64.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.7.3 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.1 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.1 which is incompatible.


In [1]:
import gensim

/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# gensim 디폴트 프리트레인 모델 불러오기 (구글 뉴스 말뭉치 학습 모델)
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

[=================================================-] 99.9% 1661.9/1662.8MB downloaded


In [3]:
# 학습된 king 이라는 단어의 벡터 확인
print(wv['king'].shape)
wv['king']

(300,)


array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [4]:
# 학습되지 않은 'cameroon'이라는 단어의 벡터 확인
try:
  wv['cameroon']
except:
  print('해당 모델에 학습되지 않은 단어 ')

해당 모델에 학습되지 않은 단어 


In [5]:
# 두 단어간 유사도 파악
pairs = [
    ('car', 'minivan'),   
    ('car', 'bicycle'),  
    ('car', 'airplane'),
    ('car', 'cereal'),    
    ('car', 'democracy')
]

for w1, w2 in pairs:
    print(f'{w1} ======= {w2}\t  {wv.similarity(w1, w2):.2f}')

car ======= minivan	  0.69
car ======= bicycle	  0.54
car ======= airplane	  0.42
car ======= cereal	  0.14
car ======= democracy	  0.08


In [12]:
# 가장 잘 맞는 단어
wv.most_similar('car',
                topn=10)

[('vehicle', 0.7821096181869507),
 ('cars', 0.7423831224441528),
 ('SUV', 0.7160962224006653),
 ('minivan', 0.6907036900520325),
 ('truck', 0.6735789775848389),
 ('Car', 0.6677608489990234),
 ('Ford_Focus', 0.667320191860199),
 ('Honda_Civic', 0.6626849174499512),
 ('Jeep', 0.651133120059967),
 ('pickup_truck', 0.6441438794136047)]

In [16]:
# 단어 덩어리 중 가장 매치가 안되는 단어
wv.doesnt_match(['fire', 'water', 'land', 'sea', 'air', 'car'])

'car'

In [13]:
# 벡터의 합 positive 메서드
for i, (word, similarity) in enumerate(wv.most_similar(positive=['coffe', 'sugar'], topn=5)):
  print(f'top{i+1}: {word}, {similarity}')

top1: coffee, 0.6647744178771973
top2: suger, 0.6409335136413574
top3: turbinado, 0.6205686926841736
top4: strawberry_smoothie, 0.6185998916625977
top5: HobNobs, 0.613012969493866


In [15]:
# 벡터의 차 negative
wv.most_similar(positive=['king', 'women'], negative=['men'], topn=1) # king + women - men

[('queen', 0.6525818109512329)]

### gensim 문장 분류기

문장의 벡터 = 문장을 이루는 모든 벡터값의 평균 벡터

In [17]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.datasets import imdb

데이터셋 불러오기 

In [18]:
tf.random.set_seed(42)

In [19]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=20000)

17464789/17464789 [==============================] - 1s 0us/step


In [52]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [20]:
print(f"Train set shape : {X_train.shape}")
print(f"Test set shape : {X_test.shape}")

Train set shape : (25000,)
Test set shape : (25000,)


In [22]:
X_train[0][:10] # 인코딩 되어있다

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65]

In [24]:
# 디코딩 함수 
word_index = imdb.get_word_index()
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

def decode_review(text):
    """
    word_index 를 받아서 text 를 sequence 형태로 반환하는 함수입니다.

    Args:
        text: 텍스트 시퀀스입니다 -> str
    """
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

1641221/1641221 [==============================] - 0s 0us/step


In [31]:
decode_review(X_train[0])

"the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room and it so heart shows to years of every never going and help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but pratfalls to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other tricky in of seen over landed for anyone of and br show's to whether from than out themselves history he name half some br of 'n odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but when from one bit the

### 토크나이징 

In [33]:
# 학습데이터 디코딩
sentences = [decode_review(idx) for idx in X_train]

# 케라스 토크나이저 선언
tokenizer = Tokenizer()

# 케라스 토크나이저 학습
tokenizer.fit_on_texts(sentences)

In [37]:
# 단어사전 확인
# tokenizer.word_index

In [38]:
# 토크나이징
X_encoded = tokenizer.texts_to_sequences(sentences)

In [43]:
# 토크나이징 결과 확인
X_encoded[0][:10]

[30, 12, 20, 14, 42, 528, 970, 1620, 1383, 64]

In [45]:
# 패딩
print(f'학습데이터 평균 길이: {np.mean([len(i) for i in X_train])}')

학습데이터 평균 길이: 238.71364


In [46]:
# 패딩 길이 설정
maxlen_pad = 400

# 패딩
X_train=pad_sequences(X_encoded, maxlen=maxlen_pad, padding='post')

# 타겟 벡터화
y_train=np.array(y_train)

### 단어사전에 있는 단어의 가중치만 가져오기 

In [48]:
vocab_size = len(tokenizer.word_index) + 1 # 패딩 1
embedding_matrix = np.zeros((vocab_size, 300))

In [50]:
# 단어사전에 등재된 가중치만 가져와서 embedding_matrix로 저장
def get_vector(word):
    """
    입력 단어가 vocab 에 있는 단어일 경우 임베딩 벡터를 반환
    
    Args:
        word: 입력 단어 -> str
    """
    if word in wv:
        return wv[word]
    else:
        return None

for word, i in tokenizer.word_index.items():
    temp = get_vector(word)
    if temp is not None:
        embedding_matrix[i] = temp

In [51]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.09082031, -0.21777344, -0.07226562, ...,  0.32226562,
        -0.05957031, -0.11328125],
       [-0.265625  ,  0.25585938, -0.01855469, ...,  0.0480957 ,
         0.34765625,  0.01177979],
       [-0.05541992,  0.26367188,  0.18457031, ..., -0.16503906,
        -0.25976562, -0.14257812]])

### 가중치를 케라스 모델에 적용하여 문장 분류기 만들기 

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

In [54]:
# 모델 생성
model = Sequential()

# 임베딩 층 추가
model.add(Embedding(vocab_size, 300,
                    weights=[embedding_matrix],
                    input_length=maxlen_pad,
                    trainable=False)) # 파인튜닝X 전이학습O
model.add(GlobalAveragePooling1D()) # 입력되는 단어 벡터의 평균을 구하는 레이어
model.add(Dense(1, activation='sigmoid'))

In [55]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['acc'])

In [56]:
model.fit(X_train, y_train, batch_size=64, epochs=20, validation_split=0.2)

Epoch 1/20
313/313 [==============================] - 7s 20ms/step - loss: 0.6924 - acc: 0.5268 - val_loss: 0.6907 - val_acc: 0.5998
Epoch 2/20
313/313 [==============================] - 6s 19ms/step - loss: 0.6901 - acc: 0.5767 - val_loss: 0.6882 - val_acc: 0.5972
Epoch 3/20
313/313 [==============================] - 7s 23ms/step - loss: 0.6880 - acc: 0.5899 - val_loss: 0.6859 - val_acc: 0.6006
Epoch 4/20
313/313 [==============================] - 7s 22ms/step - loss: 0.6861 - acc: 0.5918 - val_loss: 0.6837 - val_acc: 0.5928
Epoch 5/20
313/313 [==============================] - 7s 21ms/step - loss: 0.6845 - acc: 0.5949 - val_loss: 0.6824 - val_acc: 0.5970
Epoch 6/20
313/313 [==============================] - 6s 19ms/step - loss: 0.6827 - acc: 0.5957 - val_loss: 0.6800 - val_acc: 0.5946
Epoch 7/20
313/313 [==============================] - 6s 19ms/step - loss: 0.6813 - acc: 0.6028 - val_loss: 0.6787 - val_acc: 0.6112
Epoch 8/20
313/313 [==============================] - 6s 19ms/step - 

In [57]:
# 테스트 데이터도 같은 절차
test_sentences = [decode_review(idx) for idx in X_test]

X_test_encoded = tokenizer.texts_to_sequences(test_sentences)

X_test=pad_sequences(X_test_encoded, maxlen=400, padding='post')
y_test=np.array(y_test)

In [58]:
model.evaluate(X_test, y_test)

782/782 [==============================] - 7s 9ms/step - loss: 0.6680 - acc: 0.6093


[0.6679654121398926, 0.609279990196228]