# 파이토치로 단순 선형회귀모델 구현하기

In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim

In [30]:
# 시드 고정
torch.manual_seed(1)

In [12]:
# 데이터 생성
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [13]:
X_train, y_train

(tensor([[1.],
         [2.],
         [3.]]),
 tensor([[2.],
         [4.],
         [6.]]))

In [21]:
# 클래스 선언
class SimpleLinearRegression(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, 1)
        
    def forward(self, x):
        return self.linear(x)

In [22]:
input_dim = X_train.shape[1]
model = SimpleLinearRegression(input_dim)

# 옵티마이저 설정
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [32]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(X_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print(f'Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f}')

Epoch    0/2000 Cost: 0.000000
Epoch  100/2000 Cost: 0.000000
Epoch  200/2000 Cost: 0.000000
Epoch  300/2000 Cost: 0.000000
Epoch  400/2000 Cost: 0.000000
Epoch  500/2000 Cost: 0.000000
Epoch  600/2000 Cost: 0.000000
Epoch  700/2000 Cost: 0.000000
Epoch  800/2000 Cost: 0.000000
Epoch  900/2000 Cost: 0.000000
Epoch 1000/2000 Cost: 0.000000
Epoch 1100/2000 Cost: 0.000000
Epoch 1200/2000 Cost: 0.000000
Epoch 1300/2000 Cost: 0.000000
Epoch 1400/2000 Cost: 0.000000
Epoch 1500/2000 Cost: 0.000000
Epoch 1600/2000 Cost: 0.000000
Epoch 1700/2000 Cost: 0.000000
Epoch 1800/2000 Cost: 0.000000
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [33]:
# 예측 결과
model(torch.Tensor([100]))

tensor([199.9996], grad_fn=<AddBackward0>)

# 텐서플로우로 단순선형회귀모델 구현

In [62]:
import tensorflow as tf
import numpy as np

In [81]:
# 시드 고정
np.random.seed(42)
tf.random.set_seed(42)

In [82]:
# 데이터 생성
X_train = np.array([[1], [2], [3]])
y_train = np.array([[2], [4], [6]])

In [104]:
# 모델 선언
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(3, activation='sigmoid'),
    tf.keras.layers.Dense(1)
])

In [105]:
# 모델 컴파일
model.compile(optimizer='adam',
              loss='mse',
              metrics=['accuracy'])

In [106]:
# 학습
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 323ms/step - loss: 20.1031 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 20.0878 - accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 20.0725 - accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 20.0572 - accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 20.0420 - accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 20.0268 - accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 20.0116 - accuracy: 0.0000e+00
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 19.9964 - accuracy: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 19.9812 - accuracy: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 3ms/step - loss: 19.9661 - accuracy

In [107]:
model.predict(np.array([2]))

1/1 [==============================] - 0s 35ms/step


array([[-0.16241409]], dtype=float32)